# Generated by Django 5.0.4 on 2024-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='название продукта'),
        ),
    ]
