# Generated by Django 4.2.2 on 2024-05-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_is_published', 'Can edit is published'), ('can_edit_description', 'Can edit description'), ('can_edit_category', 'Can edit category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
